image: node

variables:
  TIDDLYWIKI_PLUGIN_PATH: ./plugins

stages:
  - test
  - pages

test:
  stage: test
  script:
    - npm install -g tiddlywiki
    - tiddlywiki test

pages:
  stage: pages
  script:
    - npm install -g tiddlywiki
    # Generate as index.html: single HTML demo page
    - tiddlywiki --build index
    # Generate as .json file: drag-n-drop installer
    - tiddlywiki --render '$:/plugins/bimlas/kin-filter' tw5-kin-filter.json text/plain '$:/core/templates/json-tiddler'
    # Serve a compressed version to speed up the loading
    # https://gitlab.com/gitlab-org/gitlab-pages/merge_requests/25
    - gzip --recursive --keep output
    # GitLab needs 'public' dirname for deploy
    # https://gitlab.com/gitlab-org/gitlab-ee/issues/1719
    - mv output public
  artifacts:
    paths:
    - public
  only:
    - master
